<a href="https://colab.research.google.com/github/ushafromwork/Machine-Learning/blob/main/Matrix_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#Creating a matrix using numpy

In [3]:
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [6]:
matrix_2=np.array([[10,34,25],[48,28,37],[15,38,35]])
print(matrix_2)

[[10 34 25]
 [48 28 37]
 [15 38 35]]


In [7]:
matrix_2.shape

(3, 3)

#Creating the matrices with random values

In [11]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.05683575 0.79781962 0.96168514]
 [0.66504031 0.26210576 0.41206956]
 [0.21164716 0.89315214 0.31653459]]


#creating matrix with random integers

In [14]:
random_matrix1=np.random.randint(100,size=(4,5))
# values should not exceed 100 and shape(4,5)

In [15]:
print(random_matrix1)

[[93 74 56 73 21]
 [10  8 27 93 33]
 [ 6 34 24 36 98]
 [55 91 66  8 30]]


#creating a matrix with all the values as 1

In [18]:
random_3=np.ones((2,3))
print(random_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
random_5=np.ones((2,3),dtype=int)
print(random_5)

[[1 1 1]
 [1 1 1]]


In [21]:
random_4=np.zeros((3,4))
print(random_4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
identity_matrix= np.eye(3,3)

In [25]:
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#Transpose of a matrix

In [29]:
#converting rows to columns
a=np.random.randint(100,size=(4,5))
print(a)

[[73 71 55 14 42]
 [ 4 70 28 38 78]
 [25 16  5 91 20]
 [ 9 93 25 89 12]]


In [31]:
transpose_a=np.transpose(a)
print(transpose_a)

[[73  4 25  9]
 [71 70 16 93]
 [55 28  5 25]
 [14 38 91 89]
 [42 78 20 12]]
