<a href="https://colab.research.google.com/github/ushafromwork/Machine-Learning/blob/main/Matrix_Operations_in_Python_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


**Matrix Addition**

Two matrices can be added if they have same shape

In [3]:
#creating two matrices
a=np.array([[2,3],[4,5]])
b=np.array([[6,7],[8,9]])

In [4]:
print(a)

[[2 3]
 [4 5]]


In [5]:
#shape of matrix
a.shape

(2, 2)

In [6]:
b.shape

(2, 2)

In [7]:
#Addition of two matrices
add=np.add(a,b)

In [8]:
print(add)

[[ 8 10]
 [12 14]]


In [9]:
#Creating two matrices with random values
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(20,size=(3,3))

In [10]:
matrix_add=np.add(matrix_1,matrix_2)

In [12]:
print(matrix_1)

[[0 3 6]
 [2 4 2]
 [0 2 2]]


In [13]:
print(matrix_2)

[[18 16  0]
 [ 4 18 15]
 [11  8  6]]


In [11]:
print(matrix_add)

[[18 19  6]
 [ 6 22 17]
 [11 10  8]]


In [14]:
matrix_3=np.random.randint(10,size=(3,3))
matrix_4=np.random.randint(20,size=(3,4))

In [15]:
matrix_sum=np.add(matrix_3,matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

WE get the above error because the shape of two matrices is not same

**Matrix subtraction**

In [16]:
x=np.random.randint(10,size=(3,3))
y=np.random.randint(20,size=(3,3))

In [19]:
sub=x-y
print(sub)

[[-3  0  1]
 [ 2  4  5]
 [-8 -5 -4]]


In [20]:
subtract=np.subtract(x,y)

In [21]:
print(subtract)

[[-3  0  1]
 [ 2  4  5]
 [-8 -5 -4]]


**Multiply Matrix with a scalar**

In [23]:
c=np.array([[2,3],[6,7]])
d=2

In [24]:
mult=c*d
print(mult)

[[ 4  6]
 [12 14]]


In [28]:
e=np.random.randint(10,size=(3,3))
f=4
print(e)

[[2 6 4]
 [7 0 8]
 [8 9 2]]


In [29]:
multiply=np.multiply(e,f)
print(multiply)

[[ 8 24 16]
 [28  0 32]
 [32 36  8]]


**Multiplying two matrices**

In [30]:
x1=np.random.randint(5,size=(3,3))
y1=np.random.randint(3,size=(3,4))

In [31]:
print(x1)

[[3 3 3]
 [4 4 0]
 [2 0 0]]


In [32]:
print(y1)

[[0 1 2 1]
 [2 0 2 0]
 [0 2 0 0]]


In [34]:
product=np.dot(x1,y1)
print(product)

[[ 6  9 12  3]
 [ 8  4 16  4]
 [ 0  2  4  2]]


In [35]:
product.shape

(3, 4)

In [36]:
x2=np.random.randint(5,size=(3,3))
y2=np.random.randint(3,size=(4,4))

In [37]:
product1=np.dot(x2,y2)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

The above error explains that shape of the two matrices should be aligned to perform multiplication,first matrix column and 2nd matrix row should be same

**Element wise matrix multiplication**

shape should be same of two matrices

In [39]:
x3=np.random.randint(5,size=(3,3))
y3=np.random.randint(5,size=(3,3))

In [40]:
print(x3,y3)

[[2 4 1]
 [4 2 3]
 [0 4 3]] [[4 4 3]
 [0 2 0]
 [2 4 2]]


In [41]:
product3=np.multiply(x3,y3)

In [42]:
print(product3)

[[ 8 16  3]
 [ 0  4  0]
 [ 0 16  6]]
