<a href="https://colab.research.google.com/github/ushafromwork/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Numpy Arrays

In [2]:
list_1=[1,2,3,4]
print(list_1)
type(list_1)

[1, 2, 3, 4]


list

In [3]:
np_array=np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [5]:
a=np.array([1,2,3,4])
print(a.shape)
a.shape

(4,)


(4,)

In [6]:
b=np.array([(1,2,3,4),(5,6,7,8)])
b.shape

(2, 4)

shape gives number of rows and columns

In [8]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial place holders in numpy arrays

In [10]:
#create a numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#create an array of ones
y=np.ones((3,2))
print(y)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [12]:
#create an array of specific value
z=np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [13]:
#create an identity matrix,rows and columns should be same
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#create a numpy array with random values
b=np.random.random((3,4))
print(b)

[[0.5320257  0.20350606 0.238188   0.82416328]
 [0.44238882 0.43235363 0.09217197 0.08720064]
 [0.99830643 0.21665672 0.19687002 0.22798906]]


In [16]:
#create random integer values array
c=np.random.randint(10,100,(3,5))
print(c)

[[65 64 34 49 24]
 [82 91 65 38 18]
 [30 23 51 60 15]]


In [17]:
#array of evenly spaced values---specifying number of values required
d=np.linspace(10,50,5)
print(d)

[10. 20. 30. 40. 50.]


In [18]:
#array of evenly spaced values--specifying the step
e=np.arange(10,50,5)
print(e)

[10 15 20 25 30 35 40 45]


In [22]:
#convert a list to an array
list2=[2,3,4,5]
np_array=np.asarray(list2)
print(np_array)

[2 3 4 5]


In [25]:
#Analyzing a numpy array
c=np.random.randint(10,90,(5,5))
print(c)

[[51 27 50 76 72]
 [82 15 25 77 42]
 [47 28 53 89 38]
 [86 39 50 71 20]
 [31 50 12 27 38]]


In [29]:
#array dimension
#no.of dimensions
#no.of elements
#data type of a numpy array
print(c.shape)
print(c.ndim)
print(c.size)
print(c.dtype)

(5, 5)
2
25
int64


Mathematical operations on a numpy array

In [30]:
list1=[1,2,3,4]
list2=[5,6,7,8]
print(list1 +list2) # concatenate or joins

[1, 2, 3, 4, 5, 6, 7, 8]


In [32]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(20,30,(3,3))
print(a,b)
print(a+b)
print(a-b)
print(a/b)
print(a*b)

[[3 4 7]
 [3 8 8]
 [7 6 1]] [[23 25 26]
 [28 27 26]
 [24 29 21]]
[[26 29 33]
 [31 35 34]
 [31 35 22]]
[[-20 -21 -19]
 [-25 -19 -18]
 [-17 -23 -20]]
[[0.13043478 0.16       0.26923077]
 [0.10714286 0.2962963  0.30769231]
 [0.29166667 0.20689655 0.04761905]]
[[ 69 100 182]
 [ 84 216 208]
 [168 174  21]]


In [34]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(20,30,(3,3))
print(a)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[8 9 8]
 [9 1 5]
 [5 5 9]]
[[28 21 29]
 [27 22 28]
 [23 27 25]]
[[36 30 37]
 [36 23 33]
 [28 32 34]]
[[-20 -12 -21]
 [-18 -21 -23]
 [-18 -22 -16]]
[[224 189 232]
 [243  22 140]
 [115 135 225]]
[[0.28571429 0.42857143 0.27586207]
 [0.33333333 0.04545455 0.17857143]
 [0.2173913  0.18518519 0.36      ]]


Array Manipulation

In [35]:
array=np.random.randint(0,10,(2,3))
print(array)
array.shape

[[2 5 4]
 [6 4 7]]


(2, 3)

In [36]:
trans=np.transpose(array)
print(trans)
trans.shape

[[2 6]
 [5 4]
 [4 7]]


(3, 2)

In [37]:
array=np.random.randint(0,10,(2,3))
print(array)
array.shape

[[2 6 3]
 [2 4 4]]


(2, 3)

In [38]:
#Another way of reversing shape of an array
trans2=array.T
print(trans2)
trans2.shape

[[2 2]
 [6 4]
 [3 4]]


(3, 2)

In [39]:
array=np.random.randint(0,10,(2,3))
print(array)
array.shape

[[8 9 9]
 [9 3 1]]


(2, 3)

In [40]:
b=array.reshape(3,2)
print(b)
b.shape

[[8 9]
 [9 9]
 [3 1]]


(3, 2)